# Create Go Docker image build and publish stages.
parameters:
  extraParameters: {}

stages:
  - template: ../../common/templates/stages/build-test-publish-repo.yml
    parameters:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
      noCache: true
      # Template paths must be relative to the YAML job that executes them
      customBuildInitSteps:
        - template: ../../../pipelines/steps/set-imagebuilder-build-args-var.yml
        - template: ../../../pipeline/steps/set-public-source-branch-var.yml
      customPublishInitSteps:
        - template: ../../../pipeline/steps/set-public-source-branch-var.yml
      # Specific pools for arm builds.
      linuxArm64Pool:
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          name: DotNetCoreDocker-Public
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          name: Docker-Linux-Arm-Internal
      linuxArm32Pool:
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
          name: DotNetCoreDocker-Public
        ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
          name: Docker-Linux-Arm-Internal
      # On Windows, 'docker login' is incompatible with 'manifest-tool' unless we use these pools.
      # https://github.com/dotnet/docker-tools/issues/905
      windows2016Pool: Docker-2016-${{ variables['System.TeamProject'] }}
      windows1809Pool: Docker-1809-${{ variables['System.TeamProject'] }}
      windows2022Pool: Docker-2022-${{ variables['System.TeamProject'] }}

      ${{ each pair in parameters.extraParameters }}:
        ${{ pair.key }}: ${{ pair.value }}
