# Create Go Docker image build and publish stages.
parameters:
  extraParameters: []

stages:
  - template: ../../common/templates/stages/build-test-publish-repo.yml
    parameters:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
      noCache: true
      internalProjectName: ${{ variables.internalProjectName }}
      publicProjectName: ${{ variables.publicProjectName }}
      # Template paths must be relative to the YAML job that executes them
      customBuildInitSteps:
        - template: ../../../pipeline/steps/set-public-source-branch-var.yml
      customPublishInitSteps:
        - template: ../../../pipeline/steps/set-public-source-branch-var.yml
      # On Windows, 'docker login' is incompatible with 'manifest-tool' unless we use these pools.
      # https://github.com/dotnet/docker-tools/issues/905
      windows2016Pool: Docker-2016-${{ variables['System.TeamProject'] }}
      windows1809Pool: Docker-1809-${{ variables['System.TeamProject'] }}
      windows2004Pool: Docker-2004-${{ variables['System.TeamProject'] }}
      windows20H2Pool: Docker-20H2-${{ variables['System.TeamProject'] }}
      windows2022Pool: Docker-2022-${{ variables['System.TeamProject'] }}
      ${{ each pair in parameters.extraParameters }}:
        ${{ pair.key }}: ${{ pair.value }}
