# Check that Dockerfile generation using "dockerupdate" is repeatable. This makes sure the patches
# apply to the current submodule commit, the manifest.json file is up to date, versions.json is
# valid, and the Dockerfiles are generated correctly, all using a known version of "dockerupdate".
parameters:
  extraParameters: {}

stages:
  - stage: Repeatability
    dependsOn: []
    jobs:
      - job: Test
        pool:
          # This is a utility job: use generic recent LTS.
          ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.publicProjectName) }}:
            name: NetCore-Public
            demands: ImageOverride -equals 1es-ubuntu-2004-open
          ${{ if eq(variables['System.TeamProject'], parameters.extraParameters.internalProjectName) }}:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals 1es-ubuntu-2004
        workspace:
          clean: all
        steps:
          - template: ../steps/checkout-unix-task.yml

          - task: GoTool@0
            inputs:
              version: 1.20

          # Install the update command with the version in eng/ci-tools.
          - script: go install github.com/microsoft/go-infra/cmd/dockerupdate
            displayName: Install dockerupdate
            workingDirectory: $(Build.SourcesDirectory)/eng/ci-tools

          - script: $(go env GOPATH)/bin/dockerupdate
            displayName: Run dockerupdate

          - script: |
              set -eux
              # Add files, so new untracked files don't evade detection.
              git add .
              # Exit code 1 = differences, 0 = no differences.
              git diff --cached --exit-code -- src manifest.json
            displayName: Ensure no changes
