parameters:
- name: publishConfig
  type: object
  default: null
- name: enableDryRun
  type: boolean
  default: false
- name: internalProjectName
  type: string
  default: null
- name: publicProjectName
  type: string
  default: null
- name: age
  type: number
  default: 15

stages:
  - stage: Execute
    dependsOn: []
    jobs:
      - job: Clean
        pool:
          name: $(default1ESInternalPoolName)
          image: $(default1ESInternalPoolImage)
          os: linux
        variables:
          dryRunArg: ${{ iif(parameters.enableDryRun, '--dry-run', '') }}
        steps:
          - template: /eng/docker-tools/templates/steps/init-common.yml@self
            parameters:
              dockerClientOS: linux
              publishConfig: ${{ parameters.publishConfig }}
          - template: /eng/docker-tools/templates/steps/reference-service-connections.yml@self
            parameters:
              publishConfig: ${{ parameters.publishConfig }}
              serviceConnections:
                - ${{ parameters.publishConfig.cleanServiceConnection }}
          - template: /eng/docker-tools/templates/steps/clean-acr-images.yml@self
            parameters:
              internalProjectName: ${{ parameters.internalProjectName }}
              repo: "build-staging/*"
              acr: ${{ parameters.publishConfig.BuildRegistry }}
              action: delete
              age: ${{ parameters.age }}
          - template: /eng/docker-tools/templates/steps/clean-acr-images.yml@self
            parameters:
              internalProjectName: ${{ parameters.internalProjectName }}
              repo: "public/oss/go/*"
              acr: ${{ parameters.publishConfig.BuildRegistry }}
              action: pruneEol
              age: ${{ parameters.age }}
          # Disabled due to https://github.com/dotnet/docker-tools/issues/797
          # - template: /eng/docker-tools/templates/steps/clean-acr-images.yml@self
          #   parameters:
          #     repo: "mirror/*"
          #     acr: ${{ parameters.publishConfig.BuildRegistry }}
          #     action: pruneDangling
          #     age: 0
