# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline is used to clean up old images in our Azure Container Registries.
# It's derived from https://github.com/dotnet/docker-tools/blob/main/eng/pipelines/cleanup-acr-images.yml

# official: https://dev.azure.com/dnceng/internal/_build?definitionId=1521
# unofficial: https://dev.azure.com/dnceng/internal/_build?definitionId=1522

pipelineymlgen:
  output:
    - file: cleanup-acr-images-pipeline-unofficial.yml
      data:
        official: false
    - file: cleanup-acr-images-pipeline.yml
      data:
        official: true
---

trigger: none
pr: none

# For info about runtime parameters, see https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md#runtime-parameters
parameters:
  - name: enableDryRun
    displayName: Enable Dry Run
    default: ${ yml (not .official) }
    type: boolean

  - name: disableTSA
    displayName: "[Debug input] Disable TSA reporting. Use to try modifications in dev branches."
    type: boolean
    default: ${ yml (not .official) }

  - name: age
    displayName: Age (in days) of images to clean up
    type: number
    default: 15

schedules:
  - ${ inlineif .official }:
    - cron: "0 5 * * *"
      displayName: Nightly build
      branches:
        include:
          - microsoft/main
      always: true

variables:
  - template: /eng/pipeline/variables/go-common.yml@self

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  ${ inlineif .official }:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${ inlineelse }:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      tsa:
        enabled: ${{ not(parameters.disableTSA) }}
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json
    stages:
      - template: /eng/pipeline/stages/publish-config-prod.yml@self
        parameters:
          stagesTemplate: /eng/pipeline/stages/go-cleanup-acr-images.yml@self
          stagesTemplateParameters:
            enableDryRun: ${{ parameters.enableDryRun }}
            age: ${{ parameters.age }}
