trigger: none
pr:
  branches:
    include:
      - microsoft/main

variables:
  - template: /eng/pipeline/variables/go-common.yml@self

stages:
  - template: /eng/pipeline/stages/publish-config-nonprod.yml@self
    parameters:
      sourceBuildPipelineRunId: $(Build.BuildId)
      stagesTemplate: /eng/docker-tools/templates/stages/dotnet/build-and-test.yml@self
      stagesTemplateParameters:
        sourceBuildPipelineRunId: $(Build.BuildId)
        buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group build
        noCache: true
        customGenerateMatrixInitSteps:
          - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
        customBuildInitSteps:
          - template: /eng/pipeline/steps/set-imagebuilder-build-args-var.yml@self
          - template: /eng/pipeline/steps/set-public-source-branch-var.yml@self
        buildMatrixType: platformVersionedOs

  - template: /eng/pipeline/stages/check-generation-repeatable.yml@self
    parameters:
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals build.ubuntu.2204.amd64.open
