trigger:
  batch: true
  branches:
    include:
      - microsoft/*
      - dev/official/*
pr: none

variables:
  - template: variables/common.yml

stages:
  - template: stages/build-test-publish-repo.yml
