trigger: none
pr:
  branches:
    include:
      - microsoft/*
      - dev/official/*

variables:
  - template: variables/common.yml

stages:
  - template: stages/build-test-publish-repo.yml
    parameters:
      extraParameters:
        buildMatrixType: platformVersionedOs
